version: "3.8"

services:
  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - d:/yura/postgresql:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: toor
    ports:
      - "8082:80"
