version: "3.8"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    environment:
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: toor
      CASSANDRA_START_RPC: "true"
      CASSANDRA_RPC_ADDRESS: "0.0.0.0"
      CASSANDRA_BROADCAST_RPC_ADDRESS: "127.0.0.1"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data: d:/yura/cassandra
