version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass toor
    ports:
      - "6379:6379"
    volumes:
      - d:/yura/redis:/data
